# Generated by Django 6.0.7 on 2026-10-04 22:27

import core.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        ("core", "0001_initial"),
        ("voting", "0035_secure_ballot_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="paystack", max_length=20)),
                ("event_type", models.CharField(max_length=60)),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                (
                    "reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("DUPLICATE", "Duplicate (replay)"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("payload", models.JSONField(default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=1)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Percent off"),
                            ("FIXED", "Fixed amount off"),
                            ("BONUS_VOTES", "Bonus votes"),
                        ],
                        default="PERCENT",
                        max_length=12,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("per_payer_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("redemptions_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_codes",
                        to="voting.event",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("VOTE", "Votes"),
                            ("INVOICE", "Subscription invoice"),
                        ],
                        default="VOTE",
                        max_length=10,
                    ),
                ),
                ("votes", models.PositiveIntegerField(default=0)),
                ("bonus_votes", models.PositiveIntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("payer_email", core.fields.EncryptedTextField(blank=True, default="")),
                (
                    "payer_email_index",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payer_phone", core.fields.EncryptedTextField(blank=True, default="")),
                (
                    "payer_phone_index",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payer_name", models.CharField(blank=True, max_length=150)),
                ("channel", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("PENDING", "Pending (customer at gateway)"),
                            ("SUCCESS", "Successful"),
                            ("FAILED", "Failed"),
                            ("ABANDONED", "Abandoned"),
                            ("REVERSED", "Reversed"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIALLY_REFUNDED", "Partially refunded"),
                            ("DISPUTED", "Chargeback / dispute"),
                        ],
                        db_index=True,
                        default="INITIALIZED",
                        max_length=20,
                    ),
                ),
                ("gateway_status", models.CharField(blank=True, max_length=30)),
                ("gateway_id", models.CharField(blank=True, max_length=40)),
                ("authorization_url", models.URLField(blank=True, max_length=500)),
                ("access_code", models.CharField(blank=True, max_length=100)),
                (
                    "card_signature",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("card_country", models.CharField(blank=True, max_length=4)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=30)),
                ("card_bank", models.CharField(blank=True, max_length=80)),
                ("gateway_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("gateway_paid_at", models.DateTimeField(blank=True, null=True)),
                ("risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("risk_decision", models.CharField(blank=True, max_length=10)),
                ("held", models.BooleanField(default=False)),
                ("hold_reason", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "device_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                ("votes_credited", models.BooleanField(default=False)),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="voting.candidate",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="payments.discountcode",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="voting.event",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("source", models.CharField(max_length=20)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("checked_count", models.PositiveIntegerField(default=0)),
                ("discrepancy_count", models.PositiveIntegerField(default=0)),
                ("resolved_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MISSING_LOCALLY", "Paid at gateway, unknown locally"),
                            ("STATUS_MISMATCH", "Status differs from gateway"),
                            ("AMOUNT_MISMATCH", "Amount/currency differs from gateway"),
                            (
                                "NOT_AT_GATEWAY",
                                "Successful locally, not found at gateway",
                            ),
                            ("NOT_CREDITED", "Paid but votes not credited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("local_status", models.CharField(blank=True, max_length=20)),
                ("gateway_status", models.CharField(blank=True, max_length=30)),
                (
                    "local_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gateway_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("AUTO_RESOLVED", "Auto-resolved"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("RESOLVED", "Resolved manually"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=14,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.payment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.reconciliationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested (awaiting approval)"),
                            ("APPROVED", "Approved"),
                            ("PROCESSING", "Processing at gateway"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("reverse_votes", models.BooleanField(default=True)),
                ("gateway_refund_id", models.CharField(blank=True, max_length=40)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="VotePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("votes", models.PositiveIntegerField()),
                ("bonus_votes", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("badge", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("is_promotional", models.BooleanField(default=False)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_per_payer", models.PositiveIntegerField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_packages",
                        to="voting.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "price"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.votepackage",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["event", "status"], name="payments_pa_event_i_9abc7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="uniq_payment_idempotency_key",
            ),
        ),
    ]
