# Generated by Django 6.0.7 on 2026-10-04 22:27

import core.fields
import core.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("voting", "0035_secure_ballot_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UNFREEZE", "Lift a freeze"),
                            ("EXTEND_VOTING", "Extend the voting period"),
                            ("REOPEN_VOTING", "Re-open closed voting"),
                            (
                                "BULK_CREDENTIAL_RESET",
                                "Reset all unused voter credentials",
                            ),
                            ("DECERTIFY", "Revoke result certification"),
                            ("RELEASE_LEGAL_HOLD", "Release a legal hold"),
                            ("REFUND", "Approve a large refund"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                            ("FAILED", "Execution failed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="voting.event",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ciphertext", models.TextField()),
                ("tracker", models.CharField(max_length=64, unique=True)),
                ("style_hash", models.CharField(max_length=64)),
                ("constituency_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballots",
                        to="voting.event",
                    ),
                ),
            ],
            options={
                "ordering": ["tracker"],
            },
        ),
        migrations.CreateModel(
            name="CandidateDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("file", models.FileField(upload_to="candidate_documents/")),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="voting.candidate",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Constituency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ROOT", "Whole organization"),
                            ("COLLEGE", "College"),
                            ("FACULTY", "Faculty / school"),
                            ("DEPARTMENT", "Department"),
                            ("HALL", "Hall / residence"),
                            ("HEADQUARTERS", "Headquarters"),
                            ("REGION", "Region"),
                            ("BRANCH", "Branch / chapter"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                ("path", models.CharField(blank=True, db_index=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constituencies",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="elections.constituency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "constituencies",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("filer_name", models.CharField(max_length=150)),
                ("filer_email", core.fields.EncryptedTextField()),
                ("filer_role", models.CharField(default="VOTER", max_length=40)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ELIGIBILITY", "Voter eligibility"),
                            ("CANDIDACY", "Candidate eligibility"),
                            ("CONDUCT", "Election conduct"),
                            ("TECHNICAL", "Technical problem"),
                            ("RESULT", "Result challenge"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under review"),
                            ("UPHELD", "Resolved - upheld"),
                            ("DISMISSED", "Resolved - dismissed"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="voting.event",
                    ),
                ),
                (
                    "filed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ElectionConfigSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=40)),
                ("config", models.JSONField()),
                ("config_hash", models.CharField(max_length=64)),
                ("signature", models.CharField(max_length=200)),
                ("public_key", models.CharField(max_length=64)),
                ("key_id", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_snapshots",
                        to="voting.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ElectionKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=64)),
                ("fingerprint", models.CharField(max_length=16)),
                ("custody", models.CharField(default="SYSTEM", max_length=10)),
                (
                    "wrapped_private_key",
                    core.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("threshold", models.PositiveSmallIntegerField(default=0)),
                ("shares", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "election",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ballot_key",
                        to="voting.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OFFICIAL", "Official tally"),
                            ("RECOUNT", "Recount"),
                            ("INDEPENDENT", "Independent (auditor) recount"),
                        ],
                        default="OFFICIAL",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Awaiting results review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                            ("INFORMATIONAL", "Informational (recount)"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField()),
                ("result_hash", models.CharField(max_length=64)),
                ("bulletin_root", models.CharField(blank=True, max_length=64)),
                ("ballots_counted", models.PositiveIntegerField(default=0)),
                ("eligible_voters", models.PositiveIntegerField(default=0)),
                ("votes_cast", models.PositiveIntegerField(default=0)),
                ("tallied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="voting.event",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tallied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tallied_at"],
            },
        ),
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "CONSTITUENCY",
                                "Belongs to constituency (or its sub-units)",
                            ),
                            ("ATTRIBUTE_EQUALS", "Attribute equals value"),
                            ("ATTRIBUTE_IN", "Attribute is one of values"),
                            ("ATTRIBUTE_NOT_IN", "Attribute is not one of values"),
                            ("EMAIL_DOMAIN", "Email address domain is one of values"),
                            ("VERIFIED_EMAIL", "Email address verified"),
                            ("VERIFIED_PHONE", "Phone number verified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("attribute", models.CharField(blank=True, max_length=60)),
                ("values", models.JSONField(blank=True, default=list)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "constituency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.constituency",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="voting.event",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="voting.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("impact", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("MITIGATED", "Mitigated"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="voting.event",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        storage=core.storage.get_private_storage,
                        upload_to="evidence/%Y/%m/",
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="elections.dispute",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="voting.event",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="elections.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="elections.dispute",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="elections.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual recount"),
                            ("INDEPENDENT", "Independent recount"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("matches", models.BooleanField(null=True)),
                ("differences", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compared_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="elections.electionresult",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recounts",
                        to="voting.event",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="elections.electionresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResultCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("signature", models.CharField(max_length=200)),
                ("public_key", models.CharField(max_length=64)),
                ("key_id", models.CharField(max_length=16)),
                (
                    "certified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="voting.event",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to="elections.electionresult",
                    ),
                ),
                (
                    "tallied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-certified_at"],
            },
        ),
        migrations.CreateModel(
            name="TrusteeShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("share_hash", models.CharField(max_length=64)),
                (
                    "pending_share",
                    core.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_share",
                    core.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trustee_shares",
                        to="voting.event",
                    ),
                ),
                (
                    "trustee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trustee_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", core.fields.EncryptedTextField(blank=True, default="")),
                ("email", core.fields.EncryptedTextField(blank=True, null=True)),
                (
                    "email_index",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("phone", core.fields.EncryptedTextField(blank=True, null=True)),
                (
                    "phone_index",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ELIGIBLE", "Eligible"),
                            ("VERIFIED", "Verified"),
                            ("VOTED", "Voted"),
                            ("SUSPENDED", "Suspended"),
                            ("INELIGIBLE", "Ineligible"),
                        ],
                        default="ELIGIBLE",
                        max_length=12,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=255)),
                (
                    "credential_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "credential_ciphertext",
                    core.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("credential_issued_at", models.DateTimeField(blank=True, null=True)),
                ("credential_version", models.PositiveSmallIntegerField(default=0)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sso_subject_index",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual entry"),
                            ("CSV", "CSV import"),
                            ("XLSX", "Excel import"),
                            ("API", "API"),
                            ("SELF_REGISTRATION", "Self registration"),
                            ("SSO", "Single sign-on"),
                            ("CODES", "Anonymous access codes"),
                            ("LEGACY", "Migrated"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "constituency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voters",
                        to="elections.constituency",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voters",
                        to="voting.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voter_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoteAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("CONSUMED", "Consumed"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ISSUED",
                        max_length=10,
                    ),
                ),
                ("auth_method", models.CharField(max_length=20)),
                ("ballot_style", models.JSONField(default=list)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vote_authorizations",
                        to="voting.event",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorizations",
                        to="elections.voter",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="constituency",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uniq_constituency_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="electionconfigsnapshot",
            constraint=models.UniqueConstraint(
                fields=("election", "version"), name="uniq_config_snapshot_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="trusteeshare",
            constraint=models.UniqueConstraint(
                fields=("election", "trustee"), name="uniq_trustee_per_election"
            ),
        ),
        migrations.AddConstraint(
            model_name="trusteeshare",
            constraint=models.UniqueConstraint(
                fields=("election", "index"), name="uniq_trustee_index"
            ),
        ),
        migrations.AddIndex(
            model_name="voter",
            index=models.Index(
                fields=["election", "status"], name="elections_v_electio_d3ae7b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identifier__isnull", False)),
                fields=("election", "identifier"),
                name="uniq_voter_identifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="voter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credential_hash__isnull", False)),
                fields=("election", "credential_hash"),
                name="uniq_voter_credential",
            ),
        ),
        migrations.AddConstraint(
            model_name="voteauthorization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CONSUMED")),
                fields=("voter",),
                name="one_consumed_authorization_per_voter",
            ),
        ),
    ]
