# Generated by Django 6.0.7 on 2026-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetransaction',
            name='number_of_votes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
