# Generated by Django 6.0.7 on 2026-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Music', 'Music'), ('Charity', 'Charity'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
