# Generated by Django 6.0.7 on 2026-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accent_color',
            field=models.CharField(default='#FFD700', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_color',
            field=models.CharField(default='#800020', max_length=7),
        ),
    ]
