# Generated by Django 6.0.7 on 2026-07-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_event_accent_color_event_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=4),
        ),
    ]
