# Generated by Django 6.0.7 on 2026-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_backgrounds/'),
        ),
    ]
