# Generated by Django 6.0.7 on 2026-07-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_candidate_category_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
