# Generated by Django 6.0.7 on 2026-07-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_mode',
            field=models.CharField(choices=[('Pay to Vote', 'Pay to Vote'), ('Code Voting', 'Code Voting')], default='Pay to Vote', max_length=20),
        ),
        migrations.CreateModel(
            name='VotingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='BDD39E1F', max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_codes', to='voting.event')),
            ],
        ),
    ]
