# Generated by Django 6.0.7 on 2026-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_event_voting_mode_votingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcode',
            name='voter_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='67D79D5A', max_length=50, unique=True),
        ),
    ]
