# Generated by Django 6.0.7 on 2026-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_votingcode_voter_identifier_alter_votingcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code_voting_mode',
            field=models.CharField(choices=[('Standard', 'Standard Codes'), ('Student ID', 'Student ID + Code')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='7F3AE54C', max_length=50, unique=True),
        ),
    ]
