# Generated by Django 6.0.7 on 2026-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_event_code_voting_mode_alter_votingcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nominee_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='B8307B8A', max_length=50, unique=True),
        ),
    ]
