# Generated by Django 6.0.7 on 2026-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0022_alter_votingcode_code_ticket_ticketpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='2B948734', max_length=50, unique=True),
        ),
    ]
