# Generated by Django 6.0.7 on 2026-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0023_ticketpurchase_buyer_name_alter_votingcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='89B9489C', max_length=50, unique=True),
        ),
    ]
