# Generated by Django 6.0.7 on 2026-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0024_ticketpurchase_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/'),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='AA93152E', max_length=50, unique=True),
        ),
    ]
