# Generated by Django 6.0.7 on 2026-07-31 12:04

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0025_ticket_image_alter_votingcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votetransaction',
            name='vote_type',
            field=models.CharField(choices=[('Main', 'Main Vote'), ('Tie-Breaker', 'Tie-Breaker Vote')], default='Main', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/', validators=[voting.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_backgrounds/', validators=[voting.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_flyers/', validators=[voting.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[voting.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/', validators=[voting.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='4CEB1B04', max_length=50, unique=True),
        ),
    ]
