# Generated by Django 6.0.7 on 2026-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_ticketpurchase_has_voted_votetransaction_vote_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='9D277138', max_length=50, unique=True),
        ),
    ]
