# Generated by Django 6.0.7 on 2026-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0027_ticket_old_price_alter_votingcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_tie_breaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='purchase_method',
            field=models.CharField(choices=[('Web', 'Web'), ('USSD', 'USSD')], default='Web', max_length=10),
        ),
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='2947E7F0', max_length=50, unique=True),
        ),
    ]
