# Generated by Django 6.0.7 on 2026-08-13 11:47

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0028_event_enable_tie_breaker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingcode",
            name="code",
            field=models.CharField(
                default=voting.models.generate_voting_code, max_length=50, unique=True
            ),
        ),
    ]
