# Generated by Django 6.0.7 on 2026-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0029_alter_votingcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vote_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
