# Generated by Django 6.0.7 on 2026-08-16 13:49

import django.db.models.deletion
import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0030_event_vote_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', validators=[voting.models.validate_file_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voting.product')),
            ],
        ),
    ]
