# Generated by Django 6.0.7 on 2026-08-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0031_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
