# Generated by Django 6.0.7 on 2026-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0032_event_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default='6A3024CF', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='votingcode',
            unique_together={('event', 'code')},
        ),
    ]
