# Generated by Django 6.0.7 on 2026-08-19 02:28

import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0033_alter_votingcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingcode',
            name='code',
            field=models.CharField(default=voting.models.generate_voting_code, max_length=50),
        ),
    ]
