# Generated by Django 6.0.7 on 2026-08-27, hand-edited to backfill code_hash
# for existing rows before the (event, code_hash) uniqueness constraint is
# re-applied - every pre-existing VotingCode would otherwise share the same
# blank code_hash and collide on the very first save.

from django.db import migrations, models

from voting.models import hash_voting_code


def backfill_code_hash(apps, schema_editor):
    VotingCode = apps.get_model("voting", "VotingCode")
    for voting_code in VotingCode.objects.all().iterator():
        voting_code.code_hash = hash_voting_code(voting_code.event_id, voting_code.code)
        voting_code.save(update_fields=["code_hash"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0034_alter_votingcode_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votingcode",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="allow_abstain",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="max_select",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="category",
            name="min_select",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="event",
            name="voting_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="votingcode",
            name="code_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="votingcode",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="votingcode",
            name="voter_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(backfill_code_hash, noop_reverse),
        migrations.AlterUniqueTogether(
            name="votingcode",
            unique_together={("event", "code_hash")},
        ),
    ]
