# Generated by Django 6.0.7 on 2026-10-04 22:27

import django.db.models.deletion
import django.utils.timezone
import voting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("elections", "0001_initial"),
        ("payments", "0001_initial"),
        ("voting", "0035_secure_ballot_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AddField(
            model_name="candidate",
            name="affiliation",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="candidate",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="candidate",
            name="manifesto",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="max_votes_per_voter",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("DISQUALIFIED", "Disqualified"),
                    ("ELIMINATED", "Eliminated"),
                ],
                default="ACTIVE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidacies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="ballot_type",
            field=models.CharField(
                choices=[
                    ("SINGLE", "Single choice"),
                    ("FPTP", "First-past-the-post (plurality, multi-seat capable)"),
                    ("MULTIPLE", "Multiple choice (choose up to N)"),
                    ("APPROVAL", "Approval voting"),
                    ("RANKED", "Ranked choice (IRV / STV)"),
                    ("SCORE", "Score / custom scoring"),
                    ("REFERENDUM", "Yes / No referendum"),
                ],
                default="SINGLE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="constituency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="elections.constituency",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="max_score",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="category",
            name="max_votes_per_voter",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="referendum_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Percent of valid votes that must be YES (strictly more).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="seats",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="category",
            name="vote_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="allow_self_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="allowed_countries",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="auth_methods",
            field=models.JSONField(
                blank=True, default=voting.models.default_auth_methods
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ballot_frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="candidates_frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="certified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="config_frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.CharField(default="GHS", max_length=3),
        ),
        migrations.AddField(
            model_name="event",
            name="dual_approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="key_custody",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "Platform key management (KMS/KEK)"),
                    ("TRUSTEES", "Split between election trustees (k-of-n)"),
                ],
                default="SYSTEM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="legal_hold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="max_spend_per_voter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_votes_per_transaction",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="max_votes_per_voter",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Per payer (email/phone/card) for the whole election.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_anonymity_set",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="event",
            name="min_votes_per_transaction",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="event",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="record_constituency_on_ballot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_email_domains",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated, e.g. st.ug.edu.gh",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="require_second_factor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="results_visibility",
            field=models.CharField(
                choices=[
                    ("LIVE", "Live counts while voting is open"),
                    ("AFTER_CLOSE", "Hidden until voting closes"),
                    (
                        "AFTER_PUBLISH",
                        "Hidden until results are certified and published",
                    ),
                ],
                default="LIVE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEW", "In review"),
                    ("APPROVED", "Approved"),
                    ("SCHEDULED", "Scheduled"),
                    ("OPEN", "Open"),
                    ("PAUSED", "Paused"),
                    ("CLOSED", "Closed"),
                    ("TALLYING", "Tallying"),
                    ("CERTIFIED", "Certified"),
                    ("PUBLISHED", "Results published"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(default="Africa/Accra", max_length=64),
        ),
        migrations.AddField(
            model_name="event",
            name="trustee_threshold",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="voter_list_frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="votetransaction",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vote_transaction",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="code_voting_mode",
            field=models.CharField(
                choices=[
                    ("Standard", "Access code only"),
                    ("Student ID", "Voter ID + access code"),
                ],
                default="Standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="voting_mode",
            field=models.CharField(
                choices=[
                    ("Pay to Vote", "Paid public voting"),
                    ("Code Voting", "Institutional election (secret ballot)"),
                ],
                default="Pay to Vote",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="votetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Failed", "Failed"),
                    ("Reversed", "Reversed (refund/chargeback)"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_date"], name="voting_even_status_c47ea3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "end_date"], name="voting_even_status_d70a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="votetransaction",
            index=models.Index(
                fields=["candidate", "status", "vote_type"],
                name="voting_vote_candida_57e1aa_idx",
            ),
        ),
    ]
