# Generated by Django 6.0.7 on 2026-10-04 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("voting", "0035_secure_ballot_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlocklistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("IP", "IP address"),
                            ("CIDR", "IP range (CIDR)"),
                            ("EMAIL", "Email address"),
                            ("EMAIL_DOMAIN", "Email domain"),
                            ("PHONE", "Phone number"),
                            ("DEVICE", "Device"),
                            ("CARD", "Card signature"),
                            ("ANONYMIZER", "Tor exit / proxy / VPN range (CIDR)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("value", models.CharField(max_length=128)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "blocklist entries",
            },
        ),
        migrations.CreateModel(
            name="FraudEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment"),
                            ("VOTE", "Vote"),
                            ("VOTER_LOGIN", "Voter sign-in"),
                            ("STAFF_LOGIN", "Staff sign-in"),
                            ("REGISTRATION", "Registration"),
                            ("ANOMALY", "Traffic anomaly"),
                            ("CHARGEBACK", "Chargeback / reversal"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow (normal)"),
                            ("MONITOR", "Monitor"),
                            ("CHALLENGE", "Challenge / verify"),
                            ("HOLD", "Hold for review"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("signals", models.JSONField(default=list)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_hash", models.CharField(blank=True, max_length=64)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CONFIRMED", "Confirmed fraud"),
                            ("DISMISSED", "Dismissed (legitimate)"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="voting.candidate",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_events",
                        to="voting.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
