# Generated by Django 6.0.8 on 2026-10-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_append_only_triggers"),
        ("fraud", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocklistentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.organization",
            ),
        ),
    ]
